[package]
name = "postgres"
version = "0.6.5"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "A native PostgreSQL driver"
repository = "https://github.com/sfackler/rust-postgres"
documentation = "https://sfackler.github.io/rust-postgres/doc/postgres"
readme = "README.md"
keywords = ["database", "sql"]

[lib]
name = "postgres"
path = "src/lib.rs"
test = false
bench = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
phf = "0.6"
phf_macros = "0.6"
openssl = "0.4.0"
time = "0.1.14"
log = "0.2"
rustc-serialize = "0.2"
byteorder = "0.2"

[dependencies.uuid]
optional = true
version = "0.1"

[dependencies.unix_socket]
optional = true
version = "0.1"

[dev-dependencies]
url = "0.2"
